using System.Collections.Concurrent;
using System.Diagnostics;
using System.Text;
using System.Text.Json;

namespace RedCompute.Plugin.Codex;

/// <summary>
/// A single JSON-RPC 2.0 connection to <c>codex app-server</c> over stdio (newline-delimited JSON).
///
/// The app-server is the same protocol every OpenAI Codex surface speaks (CLI, desktop, IDE), so
/// threads created here are visible to, and resumable from, those surfaces too. Protocol schema is
/// vendored at docs/codex-app-server-schema/ — that bundle is authoritative, generated by
/// <c>codex app-server generate-json-schema</c>.
///
/// Lifetime is owned by the caller: one connection per interactive session, or a short-lived one
/// for stateless queries like model/list.
/// </summary>
public sealed class CodexAppServerConnection : IAsyncDisposable
{
    private readonly Process _process;
    private readonly CancellationTokenSource _cts = new();
    private readonly SemaphoreSlim _writeLock = new(1, 1);
    private readonly ConcurrentDictionary<int, TaskCompletionSource<JsonElement>> _pending = new();
    private readonly Action<string, Guid?> _log;
    private int _nextRequestId;
    private volatile bool _disposed;

    /// <summary>Server-initiated notification: (method, params). Params may be default if absent.</summary>
    public event Action<string, JsonElement>? Notification;

    /// <summary>
    /// Server-initiated request needing a reply: (id, method, params). Handler must call
    /// <see cref="RespondAsync"/> or <see cref="RespondErrorAsync"/>, or the server-side turn stalls.
    /// </summary>
    public event Action<JsonElement, string, JsonElement>? ServerRequest;

    /// <summary>Raised when the underlying process exits, expectedly or not.</summary>
    public event Action<int>? Exited;

    public int ProcessId { get; }
    public JsonElement InitializeResult { get; private set; }

    private CodexAppServerConnection(Process process, Action<string, Guid?> log)
    {
        _process = process;
        _log = log;
        ProcessId = process.Id;
    }

    /// <summary>
    /// Spawns <c>codex app-server</c> and completes the initialize/initialized handshake.
    /// Throws if the CLI cannot be found or the handshake does not complete.
    /// </summary>
    public static async Task<CodexAppServerConnection> StartAsync(
        string? configuredCliPath,
        string? workingDirectory,
        Action<string, Guid?> log,
        IReadOnlyDictionary<string, string>? env = null,
        CancellationToken ct = default)
    {
        var exe = CodexCliLocator.Resolve(configuredCliPath)
            ?? throw new InvalidOperationException(
                "Could not find the 'codex' CLI. Install @openai/codex globally or set CodexPath in provider config.");

        var startInfo = new ProcessStartInfo
        {
            FileName = exe,
            CreateNoWindow = true,
            UseShellExecute = false,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            StandardInputEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8,
        };
        startInfo.ArgumentList.Add("app-server");

        if (!string.IsNullOrWhiteSpace(workingDirectory) && Directory.Exists(workingDirectory))
            startInfo.WorkingDirectory = workingDirectory;

        if (env is not null)
            foreach (var (k, v) in env)
                startInfo.EnvironmentVariables[k] = v;

        var process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Failed to start 'codex app-server'.");

        var conn = new CodexAppServerConnection(process, log);
        process.EnableRaisingEvents = true;
        process.Exited += (_, _) =>
        {
            var code = 0;
            try { code = process.ExitCode; } catch { }
            conn.FailAllPending(new IOException($"codex app-server exited with code {code}"));
            conn.Exited?.Invoke(code);
        };

        _ = Task.Run(() => conn.ReadStdoutAsync(), CancellationToken.None);
        _ = Task.Run(() => conn.ReadStderrAsync(), CancellationToken.None);

        conn.InitializeResult = await conn.SendRequestAsync("initialize", new
        {
            clientInfo = new { name = "redcompute", title = "RedCompute", version = "0.2.0" },
        }, timeoutSeconds: 30, ct);

        await conn.SendNotificationAsync("initialized", null, ct);
        return conn;
    }

    public async Task<JsonElement> SendRequestAsync(
        string method, object? @params = null, int timeoutSeconds = 60, CancellationToken ct = default)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        var id = Interlocked.Increment(ref _nextRequestId);
        var tcs = new TaskCompletionSource<JsonElement>(TaskCreationOptions.RunContinuationsAsynchronously);
        _pending[id] = tcs;

        try
        {
            await WriteLineAsync(JsonSerializer.Serialize(new { jsonrpc = "2.0", id, method, @params }), ct);

            using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(_cts.Token, ct);
            timeoutCts.CancelAfter(TimeSpan.FromSeconds(timeoutSeconds));
            return await tcs.Task.WaitAsync(timeoutCts.Token);
        }
        catch (OperationCanceledException) when (!ct.IsCancellationRequested && !_cts.IsCancellationRequested)
        {
            throw new TimeoutException($"codex app-server request '{method}' timed out after {timeoutSeconds}s");
        }
        finally
        {
            _pending.TryRemove(id, out _);
        }
    }

    public Task SendNotificationAsync(string method, object? @params = null, CancellationToken ct = default) =>
        WriteLineAsync(JsonSerializer.Serialize(new { jsonrpc = "2.0", method, @params }), ct);

    /// <summary>Replies to a server-initiated request. <paramref name="id"/> is the raw id element.</summary>
    public Task RespondAsync(JsonElement id, object result, CancellationToken ct = default) =>
        WriteLineAsync(
            $"{{\"jsonrpc\":\"2.0\",\"id\":{id.GetRawText()},\"result\":{JsonSerializer.Serialize(result)}}}", ct);

    public Task RespondErrorAsync(JsonElement id, string message, int code = -32000, CancellationToken ct = default) =>
        WriteLineAsync(
            $"{{\"jsonrpc\":\"2.0\",\"id\":{id.GetRawText()},\"error\":{JsonSerializer.Serialize(new { code, message })}}}", ct);

    private async Task WriteLineAsync(string json, CancellationToken ct)
    {
        using var linked = CancellationTokenSource.CreateLinkedTokenSource(_cts.Token, ct);
        await _writeLock.WaitAsync(linked.Token);
        try
        {
            await _process.StandardInput.WriteLineAsync(json.AsMemory(), linked.Token);
            await _process.StandardInput.FlushAsync(linked.Token);
        }
        finally
        {
            _writeLock.Release();
        }
    }

    private async Task ReadStdoutAsync()
    {
        try
        {
            while (await _process.StandardOutput.ReadLineAsync(_cts.Token) is { } line)
            {
                if (string.IsNullOrWhiteSpace(line)) continue;

                JsonElement root;
                try { root = JsonDocument.Parse(line).RootElement.Clone(); }
                catch (JsonException)
                {
                    _log($"[Codex] Non-JSON on app-server stdout: {Truncate(line, 200)}", null);
                    continue;
                }

                Dispatch(root);
            }
        }
        catch (OperationCanceledException) { }
        catch (Exception ex)
        {
            _log($"[Codex] app-server stdout reader stopped: {ex.Message}", null);
            FailAllPending(ex);
        }
    }

    private void Dispatch(JsonElement root)
    {
        var hasId = root.TryGetProperty("id", out var id);
        var hasMethod = root.TryGetProperty("method", out var methodProp);
        var hasResult = root.TryGetProperty("result", out var result);
        var hasError = root.TryGetProperty("error", out var error);

        if (hasId && !hasMethod && (hasResult || hasError))
        {
            if (!id.TryGetInt32(out var requestId)) return;
            if (!_pending.TryRemove(requestId, out var tcs)) return;

            if (hasResult) tcs.TrySetResult(result.Clone());
            else tcs.TrySetException(new CodexAppServerException(error.ToString()));
            return;
        }

        var method = hasMethod ? methodProp.GetString() : null;
        if (method == null) return;

        root.TryGetProperty("params", out var @params);

        if (hasId)
        {
            try { ServerRequest?.Invoke(id.Clone(), method, @params); }
            catch (Exception ex) { _log($"[Codex] Server-request handler threw for '{method}': {ex.Message}", null); }
        }
        else
        {
            try { Notification?.Invoke(method, @params); }
            catch (Exception ex) { _log($"[Codex] Notification handler threw for '{method}': {ex.Message}", null); }
        }
    }

    private async Task ReadStderrAsync()
    {
        try
        {
            while (await _process.StandardError.ReadLineAsync(_cts.Token) is { } line)
                if (!string.IsNullOrWhiteSpace(line))
                    _log($"[Codex:app-server] {Truncate(line, 400)}", null);
        }
        catch (OperationCanceledException) { }
        catch { }
    }

    private void FailAllPending(Exception ex)
    {
        foreach (var key in _pending.Keys.ToList())
            if (_pending.TryRemove(key, out var tcs))
                tcs.TrySetException(ex);
    }

    private static string Truncate(string s, int max) => s.Length > max ? s[..max] + "..." : s;

    public async ValueTask DisposeAsync()
    {
        if (_disposed) return;
        _disposed = true;

        try { _cts.Cancel(); } catch { }
        FailAllPending(new ObjectDisposedException(nameof(CodexAppServerConnection)));

        try
        {
            if (!_process.HasExited)
            {
                try { _process.StandardInput.Close(); } catch { }
                // Give it a beat to shut down cleanly before killing the tree.
                using var grace = new CancellationTokenSource(TimeSpan.FromSeconds(3));
                try { await _process.WaitForExitAsync(grace.Token); }
                catch (OperationCanceledException) { _process.Kill(entireProcessTree: true); }
            }
        }
        catch { }

        _process.Dispose();
        _cts.Dispose();
        _writeLock.Dispose();
    }
}

public sealed class CodexAppServerException(string message) : Exception(message);
